### PR TITLE
Update for compatibility with symfony/serializer 7

### LINKED ISSUE #45: Error in JaneObjectNormalizer after updating symfony/serializer to 7.x
After updating the symfony/serializer package from 6 to 7, the following error is generated:

Declaration of JoliCode\Harvest\Api\Normalizer\JaneObjectNormalizer::denormalize($data, $class, $format = null, array $context = []) must be compatible with Symfony\Component\Serializer\Normalizer\DenormalizerInterface::denormalize(mixed $data, string $type, ?string $format = null, array $context = []): mixed

There is also a similar error for the normalize method. The symfony/serializer is a dependency of jane-php/open-api-runtime, though it is just a dev requirement and doesn't need to be used in production deployments. It will happily use versions ^5.4, ^6.4 or ^7.0 of the serializer, so not everyone will necessarily run into this if whatever project they are using this library in does not end up installing a 7.x version of the serializer. It would all depend on how composer determines which set of packages are needed to make all the dependencies work.

I ran a composer update on Laravel 9 with PHP 8.2 and it upgraded the serializer from 6 to 7. It's easy enough to update the JaneObjectNormalizer to be compatible, but that may impact it's compatibility with older versions. I don't know the best way to handle that, but I will submit a pull request to provide a patch and leave it to people who are smarter than be to figure out how to make it compatible with all possible versions that may be used.

### PR DESCRIPTION
**Pull request by theteknocat**
Updated the function signatures of normalize and denormalize to match those defined by the interfaces being called for. Also updated the denormalize method to use an updated argument name.

Resolves #45.

### CODE REVIEW

**Comment by finwe** [comment]
I just ran into the same incompatibility and thanks for the effort, just my two cents: shouldn't this update also include updating/setting up the used `jane-php/open-api-runtime` utility and the code regenerated by it, instead of seemingly updating the files somewhat manually?

**Comment by xavierlacot** [comment]
So here it is: #47

By upgrading Jane and letting it re-generate the SDK, it has automatically added a compat layer, so this new version will work in environments with recent or older versions of the serializer.

See for example the class `BillableRatesNormalizer`: 

https://github.com/jolicode/harvest-php-api/blob/106493cf6de79c697245fa2d098434fc76080a5b/generated/Normalizer/BillableRatesNormalizer.php#L25-L249

@theteknocat can you please test the branch associated with #47 in your environment to check that it works well?

If you do not mind, I am going to merge #47 and I'll let you close this one?
In any case, thank you a lot for your help, it is very much appreciated!

**Comment by theteknocat** [comment]
@xavierlacot @finwe thanks for your responses and for flagging the correct way to do this. I had no idea how to wonk with the Jane php api, so this is definitely the better solution and having a compatibility layer that works with both versions is ideal.

Of course this now creates a conflict with the commit I made to the manually updated generated code, but that can be reverted easily enough. I'll try to find some time in the next few days to test this in my environment and see if it works.

**Comment by theteknocat** [comment]
@xavierlacot after updating my codebase to use v7.0, everything works as expected. Thanks so much for taking care of that!

**Pull request closed without merging**
